FROM node:20 AS base
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

FROM node:20-alpine3.19 AS release
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app .

EXPOSE 3000

CMD ["npm", "run", "dev"]
