FROM node:20 AS base
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine3.19 AS release
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY --from=base /app/package.json ./package.json
COPY --from=base /app/.next ./.next
COPY --from=base /app/public ./public
COPY --from=base /app/messages ./messages
COPY --from=base /app/i18n ./i18n
COPY --from=base /app/next.config.js ./next.config.js

EXPOSE 3000

CMD ["npm", "run", "start"]
